names:
  - ssq
  - dlt
start: 03001
end: 99999
base_url: "https://datachart.500.com/{name}/history/newinc/history.php"

logging:
  log_file: 'logs/app.log'
  log_level: 'DEBUG'
  max_bytes: 10485760  # 10MB
  backup_count: 5

